server:
  port: 9002

spring:
  profiles:
    active: console-logging
  application:
    name: careerwry-posting
  datasource:
    url: jdbc:mysql://localhost:3306/careerwry-posting
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: careerwry
    password: 1q2w3e4r
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    baseline-on-migrate: true # 기본 false 로 두고 필요하다면 true 를 주입하여 사용
    baseline-version: 0.0.1
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379

logging:
  config: classpath:logback-spring.xml
  level:
    org:
      springframework: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/
    registerWithEureka: true
    fetchRegistry: true
    rest-template-timeout:
      connect-timeout: 5000
      connect-request-timeout: 8000
      socket-timeout: 10000